# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Alberto Dell'Era's blog"
email: alberto.dellera@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I’ve spent all my professional life working within the Italian Telecommunications sector since 1996, 
  specializing in the Oracle database full-time since 1999. I currently work for a big (2600+ employees) consultancy firm 
  as an Oracle specialist, very often optimizing customers’ systems (“Performance Tuning”), and developing for the flagship 
  customer Web portal of one of the largest Italian mobile operators. 
  
  I also hold a Math-oriented degree in Electronics Engineering from the “Politecnico di Milano” University.

  I am honoured of being a member of OakTable Network, the famous organization of Oracle professionals distinguished by the use 
  of the Scientific Method (and related ethics) for all their activities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  alberto-dellera
linkedin_username: adellera

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
